# Generated by Django 6.0.7 on 2026-07-23 14:24

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_categoria_prefisso_sku_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stato', models.CharField(choices=[('in_attesa_pagamento', 'In attesa di pagamento'), ('pagato', 'Pagato'), ('in_preparazione', 'In preparazione'), ('spedito', 'Spedito'), ('completato', 'Completato'), ('annullato', 'Annullato'), ('rimborsato', 'Rimborsato')], default='in_attesa_pagamento', max_length=30)),
                ('stato_pagamento', models.CharField(choices=[('non_pagato', 'Non pagato'), ('pagato', 'Pagato'), ('fallito', 'Fallito'), ('rimborsato', 'Rimborsato')], default='non_pagato', max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('indirizzo', models.CharField(max_length=255)),
                ('numero_civico', models.CharField(max_length=20)),
                ('cap', models.CharField(max_length=10)),
                ('citta', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('paese', models.CharField(default='Italia', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('subtotale', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('costo_spedizione', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('totale', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('valuta', models.CharField(default='EUR', max_length=3)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordini', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordine',
                'verbose_name_plural': 'Ordini',
                'ordering': ['-data_creazione'],
            },
        ),
        migrations.CreateModel(
            name='RigaOrdine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prodotto', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=50)),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantita', models.PositiveIntegerField()),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='orders.ordine')),
                ('prodotto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='righe_ordine', to='products.prodotto')),
            ],
            options={
                'verbose_name': 'Riga ordine',
                'verbose_name_plural': 'Righe ordine',
            },
        ),
    ]
