# Generated by Django 6.1 on 2026-08-08 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_sessionecheckout_rigasessionecheckout'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='codice_tracking',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ordine',
            name='corriere',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordine',
            name='data_consegna',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordine',
            name='data_spedizione',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordine',
            name='nota_interna',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordine',
            name='url_tracking',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='stato',
            field=models.CharField(choices=[('in_attesa_pagamento', 'In attesa di pagamento'), ('pagato', 'Pagato'), ('in_preparazione', 'In preparazione'), ('spedito', 'Spedito'), ('completato', 'Consegnato'), ('annullato', 'Annullato'), ('rimborsato', 'Rimborsato')], default='in_attesa_pagamento', max_length=30),
        ),
        migrations.CreateModel(
            name='NotificaOrdine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ordine_ricevuto', 'Ordine ricevuto'), ('pagamento_confermato', 'Pagamento confermato'), ('spedizione', 'Ordine spedito'), ('annullamento', 'Ordine annullato')], max_length=30)),
                ('stato', models.CharField(choices=[('da_inviare', 'Da inviare'), ('inviata', 'Inviata'), ('errore', 'Errore')], default='da_inviare', max_length=20)),
                ('destinatario', models.EmailField(max_length=254)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_invio', models.DateTimeField(blank=True, null=True)),
                ('errore', models.TextField(blank=True)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to='orders.ordine')),
            ],
            options={
                'verbose_name': 'Notifica ordine',
                'verbose_name_plural': 'Notifiche ordine',
                'ordering': ['-data_creazione'],
            },
        ),
    ]
