# Generated by Django 6.0.7 on 2026-07-16 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='prefisso_sku',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Il prefisso può contenere soltanto lettere e numeri.', regex='^[A-Za-z0-9]+$')]),
        ),
        migrations.AddField(
            model_name='categoria',
            name='ultimo_progressivo_sku',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='sku',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Codice SKU'),
        ),
    ]
