# Generated by Django 6.1 on 2026-08-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categoria_prefisso_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='mondo',
            field=models.CharField(blank=True, choices=[('casa', 'La mia casa'), ('movimento', 'Tenersi in movimento'), ('tempo-per-me', 'Tempo per me')], default='', max_length=30, verbose_name='Mondo VivaLei'),
        ),
    ]
