# Generated by Django 6.1 on 2026-08-08 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_categoria_mondo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='prodotti/', verbose_name='Immagine principale'),
        ),
        migrations.CreateModel(
            name='ImmagineProdotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='prodotti/galleria/')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Testo alternativo')),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('principale', models.BooleanField(default=False)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immagini_extra', to='products.prodotto')),
            ],
            options={
                'verbose_name': 'Immagine prodotto',
                'verbose_name_plural': 'Immagini prodotto',
                'ordering': ['ordine', 'id'],
            },
        ),
    ]
