# Generated by Django 6.1 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_prodotto_immagine_immagineprodotto"),
    ]

    operations = [
        migrations.AddField(
            model_name="prodotto",
            name="prezzo_acquisto",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prezzo di acquisto"),
        ),
        migrations.AddField(
            model_name="prodotto",
            name="fornitore",
            field=models.CharField(blank=True, max_length=200, verbose_name="Fornitore"),
        ),
    ]
